#!/usr/bin/env python

import sys
import os

sys.path.append(os.path.abspath('../yoda'))
from yoda import Config, Output, Subcommands
from yoda.subcommand import Workspace

yoda_config = Config("%s/.yodarc" % os.environ.get("HOME"))
out = Output()

subcmd = Subcommands(yoda_config)
ws_cmd = Workspace()
subcmd.add_command(ws_cmd)
ws_cmd.load_workspaces_subcommands(subcmd)
subcmd.parse()

args = subcmd.parser.parse_args()
try:
    subcmd.execute(args)
except Exception as e:
    out.error(e)
