#!/bin/bash
# This source file is part of Yoda.
#
# Yoda is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Yoda is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Yoda. If not, see <http://www.gnu.org/licenses/gpl-3.0.html>.

function yoda_jump() {
    cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    if [[ $# -lt 1 ]]
    then
        echo >&2 "You must specify repository or workspace"
    fi

    path=$(python yoda jump $1)
    if [[ ! -d $path ]]
    then
        echo "$1 does not exists" 2>&1
    fi

    cd $path
}

